# Generated by Django 6.0.6 on 2026-06-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
