# Generated by Django 6.0.6 on 2026-07-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('IT', 'Information Technology'), ('CY', 'Cyber Security')], default='SE', max_length=2),
            preserve_default=False,
        ),
    ]
