# Generated by Django 6.0.6 on 2026-07-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='seating_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
