# Generated by Django 6.0.6 on 2026-08-30 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0003_allocation_seating_number'),
        ('exams', '0001_initial'),
        ('invigilators', '0001_initial'),
        ('students', '0003_student_department'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invigilators.invigilator')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venue')),
            ],
            options={
                'unique_together': {('exam', 'venue')},
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allocations.examsession'),
        ),
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together={('exam_session', 'seating_number'), ('student', 'exam_session')},
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='invigilator',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='venue',
        ),
    ]
